[package]
name = "ocaml-rust-starter"
version = "0.1.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
ocaml = "*"

# Or use the development version:
# ocaml = {git = "git://github.com/zshipko/ocaml-rs"}
